# Form implementation generated from reading ui file 'Ui_MouseDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Consts



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(723, 464)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(25, 25, 25, 25)
        self.layout.setSpacing(25)
        self.layout.setObjectName("layout")
        self.radio_button_layout = QtWidgets.QHBoxLayout()
        self.radio_button_layout.setObjectName("radio_button_layout")
        self.single_click_button = QtWidgets.QRadioButton(parent=Dialog)
        self.single_click_button.setObjectName("single_click_button")
        self.radio_button_layout.addWidget(self.single_click_button)
        self.double_click_button = QtWidgets.QRadioButton(parent=Dialog)
        self.double_click_button.setObjectName("double_click_button")
        self.radio_button_layout.addWidget(self.double_click_button)
        self.press_button = QtWidgets.QRadioButton(parent=Dialog)
        self.press_button.setObjectName("press_button")
        self.radio_button_layout.addWidget(self.press_button)
        self.release_button = QtWidgets.QRadioButton(parent=Dialog)
        self.release_button.setObjectName("release_button")
        self.radio_button_layout.addWidget(self.release_button)
        self.layout.addLayout(self.radio_button_layout)
        self.button_group_layout = QtWidgets.QHBoxLayout()
        self.button_group_layout.setObjectName("button_group_layout")
        self.lm_button = QtWidgets.QRadioButton(parent=Dialog)
        self.lm_button.setObjectName("lm_button")
        self.button_group_layout.addWidget(self.lm_button)
        self.rm_button = QtWidgets.QRadioButton(parent=Dialog)
        self.rm_button.setObjectName("rm_button")
        self.button_group_layout.addWidget(self.rm_button)
        self.cm_button = QtWidgets.QRadioButton(parent=Dialog)
        self.cm_button.setObjectName("cm_button")
        self.button_group_layout.addWidget(self.cm_button)
        self.layout.addLayout(self.button_group_layout)
        self.text_1 = QtWidgets.QLabel(parent=Dialog)
        self.text_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text_1.setObjectName("text_1")
        self.layout.addWidget(self.text_1)
        self.radio_button_move_layout = QtWidgets.QHBoxLayout()
        self.radio_button_move_layout.setObjectName("radio_button_move_layout")
        self.move_on_button = QtWidgets.QRadioButton(parent=Dialog)
        self.move_on_button.setObjectName("move_on_button")
        self.radio_button_move_layout.addWidget(self.move_on_button)
        self.move_in_button = QtWidgets.QRadioButton(parent=Dialog)
        self.move_in_button.setObjectName("move_in_button")
        self.radio_button_move_layout.addWidget(self.move_in_button)
        self.layout.addLayout(self.radio_button_move_layout)
        self.x_y_edit_layout = QtWidgets.QHBoxLayout()
        self.x_y_edit_layout.setContentsMargins(25, 25, 25, 25)
        self.x_y_edit_layout.setObjectName("x_y_edit_layout")
        self.x_edit_layout = QtWidgets.QFormLayout()
        self.x_edit_layout.setObjectName("x_edit_layout")
        self.x_y_edit_layout.addLayout(self.x_edit_layout)
        self.y_edit_layout = QtWidgets.QFormLayout()
        self.y_edit_layout.setObjectName("y_edit_layout")
        self.x_y_edit_layout.addLayout(self.y_edit_layout)
        self.layout.addLayout(self.x_y_edit_layout)
        self.duration_layout = QtWidgets.QFormLayout()
        self.duration_layout.setContentsMargins(25, 25, 25, 25)
        self.duration_layout.setObjectName("duration_layout")
        self.layout.addLayout(self.duration_layout)
        self.mouse_wheel_layout = QtWidgets.QFormLayout()
        self.mouse_wheel_layout.setContentsMargins(25, 25, 25, 25)
        self.mouse_wheel_layout.setObjectName("mouse_wheel_layout")
        self.layout.addLayout(self.mouse_wheel_layout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtWidgets.QPushButton(parent=Dialog)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.apply_button = QtWidgets.QPushButton(parent=Dialog)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout.addWidget(self.apply_button)
        self.layout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", Consts.MOUSE_ACTION))
        self.single_click_button.setText(_translate("Dialog", Consts.SINGLE_CLICK))
        self.double_click_button.setText(_translate("Dialog", Consts.DOUBLE_CLICK))
        self.press_button.setText(_translate("Dialog", Consts.PRESS))
        self.release_button.setText(_translate("Dialog", Consts.RELEASE))
        self.text_1.setText(_translate("Dialog", Consts.MOVE_MOUSE))
        self.move_on_button.setText(_translate("Dialog", Consts.ON))
        self.move_in_button.setText(_translate("Dialog", Consts.IN))
        self.back_button.setText(_translate("Dialog", Consts.BACK))
        self.apply_button.setText(_translate("Dialog", Consts.APPLY))
        self.lm_button.setText(_translate("Dialog", Consts.LMB))
        self.rm_button.setText(_translate("Dialog", Consts.RMB))
        self.cm_button.setText(_translate("Dialog", Consts.MOUSE_WHEEL))


