# Form implementation generated from reading ui file 'Ui_AddBindsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

import Consts

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 539)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parent_layout = QtWidgets.QVBoxLayout()
        self.parent_layout.setObjectName("parent_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.back_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_2.addWidget(self.back_button)
        self.apply_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_2.addWidget(self.apply_button)
        self.parent_layout.addLayout(self.horizontalLayout_2)
        self.line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_edit.setObjectName("line_edit")
        self.parent_layout.addWidget(self.line_edit)
        self.hotkey_layout = QtWidgets.QHBoxLayout()
        self.hotkey_layout.setObjectName("hotkey_layout")
        self.hotkey_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.hotkey_label.setObjectName("hotkey_label")
        self.hotkey_layout.addWidget(self.hotkey_label)
        self.hotkey_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hotkey_button.setObjectName("hotkey_button")
        self.hotkey_layout.addWidget(self.hotkey_button)
        self.hotkey_layout.setStretch(0, 9)
        self.hotkey_layout.setStretch(1, 1)
        self.parent_layout.addLayout(self.hotkey_layout)
        self.list_widget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.list_widget.setObjectName("list_widget")
        self.parent_layout.addWidget(self.list_widget)
        self.verticalLayout_2.addLayout(self.parent_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_button.setText(_translate("MainWindow", Consts.BACK))
        self.apply_button.setText(_translate("MainWindow", Consts.APPLY))
        self.hotkey_label.setText(_translate("MainWindow", Consts.HOTKEY +  " " + Consts.DEFAULT_HOTKEY))
        self.hotkey_button.setText(_translate("MainWindow", ""))
