# Form implementation generated from reading ui file 'Ui_BindItem.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_box = QtWidgets.QCheckBox(parent=Form)
        self.check_box.setText("")
        self.check_box.setObjectName("check_box")
        self.horizontalLayout.addWidget(self.check_box)
        self.name_label = QtWidgets.QLabel(parent=Form)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.hotkey_label = QtWidgets.QLabel(parent=Form)
        self.hotkey_label.setObjectName("hotkey_label")
        self.horizontalLayout.addWidget(self.hotkey_label)
        self.edit_button = QtWidgets.QPushButton(parent=Form)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=Form)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", ""))
        self.hotkey_label.setText(_translate("Form", ""))
        self.edit_button.setText(_translate("Form", ""))
        self.delete_button.setText(_translate("Form", ""))
