# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 539)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parent_layout = QtWidgets.QVBoxLayout()
        self.parent_layout.setObjectName("parent_layout")
        self.layout_start_stop = QtWidgets.QHBoxLayout()
        self.layout_start_stop.setContentsMargins(25, 35, 30, 25)
        self.layout_start_stop.setObjectName("layout_start_stop")
        self.emergency_stop_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergency_stop_button.sizePolicy().hasHeightForWidth())
        self.emergency_stop_button.setSizePolicy(sizePolicy)
        self.emergency_stop_button.setObjectName("emergency_stop_button")
        self.layout_start_stop.addWidget(self.emergency_stop_button)
        self.emergency_stop_button_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergency_stop_button_settings.sizePolicy().hasHeightForWidth())
        self.emergency_stop_button_settings.setSizePolicy(sizePolicy)
        self.emergency_stop_button_settings.setObjectName("emergency_stop_button_settings")
        self.layout_start_stop.addWidget(self.emergency_stop_button_settings)
        self.layout_start_stop.setStretch(0, 9)
        self.layout_start_stop.setStretch(1, 1)
        self.parent_layout.addLayout(self.layout_start_stop)
        self.layout_binds = QtWidgets.QHBoxLayout()
        self.layout_binds.setContentsMargins(25, 35, 25, 25)
        self.layout_binds.setObjectName("layout_binds")
        self.binds_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.binds_button.sizePolicy().hasHeightForWidth())
        self.binds_button.setSizePolicy(sizePolicy)
        self.binds_button.setObjectName("binds_button")
        self.layout_binds.addWidget(self.binds_button)
        self.parent_layout.addLayout(self.layout_binds)
        self.layout_add_binds = QtWidgets.QHBoxLayout()
        self.layout_add_binds.setContentsMargins(25, 35, 25, 25)
        self.layout_add_binds.setObjectName("layout_add_binds")
        self.add_binds_button = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_binds_button.sizePolicy().hasHeightForWidth())
        self.add_binds_button.setSizePolicy(sizePolicy)
        self.add_binds_button.setObjectName("add_binds_button")
        self.layout_add_binds.addWidget(self.add_binds_button)
        self.parent_layout.addLayout(self.layout_add_binds)
        self.verticalLayout_2.addLayout(self.parent_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emergency_stop_button.setText(_translate("MainWindow", "PushButton"))
        self.emergency_stop_button_settings.setText(_translate("MainWindow", "PushButton"))
        self.binds_button.setText(_translate("MainWindow", "PushButton"))
        self.add_binds_button.setText(_translate("MainWindow", "PushButton"))
